### ISSUE TITLE
Error in UseMethod("prettify") :    no applicable method for object of class "c('lmerMod', 'merMod')"

### ISSUE THREAD

**Issue by Skogur** [hofnerb/papeR#37]
From https://cran.r-project.org/web/packages/papeR/papeR.pdf :

> ## method for mixed models fitted with lme4 (vers. >= 1.0)
> ## S3 method for class 'summary.merMod'
> prettify(object, labels = NULL, sep = ": ", extra.column = FALSE,
> confint = TRUE, level = 0.95,
> smallest.pval = 0.001, digits = NULL, scientific = FALSE,
> signif.stars = getOption("show.signif.stars"),
> method = c("profile", "Wald", "boot"), B = 1000, env = parent.frame(), ...)

I am trying to prettify() lme4 models & receive this error (for any & all of the models):

```
Error in UseMethod("prettify") : 
  no applicable method for 'prettify' applied to an object of class "c('lmerMod', 'merMod')"
```

I tried with many types of lme4 models of different datasets. Same results across the board. 

Thank you for your time and effort with this package!

**Comment by hofnerb** [comment]
Please try 

```R
model <- ...
prettify(summary(model))
```
The function is only implemented for the summary of a model and not the model itself. See also the full help of `prettify` and the name of the function (`prettify.summary.merMod`).
