### ISSUE TITLE
Error in prettify(): Model can't be refitted and no labels are specified

### ISSUE THREAD

**Issue by jrosen48** [hofnerb/papeR#38]
Hi, I'm trying to `prettify()` output of a `lme4::lmer()` model. In trying to use this with my own output, I ran into some trouble, so tried to run the example, i.e.:

<br/>

    library(nlme)
    library(papeR)
    #> Loading required package: car
    #> Loading required package: xtable
    #> 
    #> Attaching package: 'papeR'
    #> The following object is masked from 'package:utils':
    #> 
    #>     toLatex
    library(lme4)
    #> Loading required package: Matrix
    #> 
    #> Attaching package: 'lme4'
    #> The following object is masked from 'package:nlme':
    #> 
    #>     lmList

    ## Fit a model for distance with random intercept for Subject
    mod4 <- lmer(distance ~ age + Sex + (1|Subject), data = Orthodont)
    summary(mod4)
    #> Linear mixed model fit by REML ['lmerMod']
    #> Formula: distance ~ age + Sex + (1 | Subject)
    #>    Data: Orthodont
    #> 
    #> REML criterion at convergence: 437.5
    #> 
    #> Scaled residuals: 
    #>     Min      1Q  Median      3Q     Max 
    #> -3.7489 -0.5503 -0.0252  0.4534  3.6575 
    #> 
    #> Random effects:
    #>  Groups   Name        Variance Std.Dev.
    #>  Subject  (Intercept) 3.267    1.807   
    #>  Residual             2.049    1.432   
    #> Number of obs: 108, groups:  Subject, 27
    #> 
    #> Fixed effects:
    #>             Estimate Std. Error t value
    #> (Intercept) 17.70671    0.83392  21.233
    #> age          0.66019    0.06161  10.716
    #> SexFemale   -2.32102    0.76142  -3.048
    #> 
    #> Correlation of Fixed Effects:
    #>           (Intr) age   
    #> age       -0.813       
    #> SexFemale -0.372  0.000
    ## Extract fixed effects table and make it pretty
    prettify(summary(mod4))
    #> Error in prettify.summary.merMod(summary(mod4)): Model can't be refitted and no labels are specified. Please specify labels.

How can I address this error: "Model can't be refitted and no labels are specified. Please specify labels."?

**Comment by hofnerb** [comment]
The error above occurs as the dataset is not available in the global environment for refitting.
If you do load the data everything works as expected:
```r
library(lme4)
data("Orthodont", package = "nlme")
library(papeR)
## Fit a model for distance with random intercept for Subject
mod4 <- lmer(distance ~ age + Sex + (1|Subject), data = Orthodont)
summary(mod4)
prettify(summary(mod4))
# Computing profile confidence intervals ...
# Confidence intervals are experimental only;
# Model refitted but original environment not available.
# 
#                 Estimate CI (lower) CI (upper) Std. Error   t value
# 1 (Intercept) 17.7067130 16.0848469 19.3285790 0.83392247 21.233044
# 2         age  0.6601852  0.5387505  0.7816198 0.06160592 10.716263
# 3 Sex: Female -2.3210227 -3.8096622 -0.8323833 0.76141685 -3.048294
```
Does this solve your underlying question?
