### ISSUE TITLE
Hello! I was wondering if the function "prettify" would be implemented for objects of class 'aov' and 'listof'?

### ISSUE THREAD

**Issue by yangwu1227** [hofnerb/papeR#46]
Hello, Mr.Benjamin. I'm an undergrad student from the US; I think that the papeR package is very useful and I use it a lot in my work. I notice that the function "prettify" is currently not implemented for an object of class like aov. Any chance that this would be implemented in the near future? Many thanks and best of luck.

**Comment by hofnerb** [comment]
Currently there are no plans to expand the package due to a lack of time on my side. However you are more than welcome to contribute such code via a pull request.

**Comment by yangwu1227** [comment]
Thnx for your response.
